### PR TITLE
Feature/Update default language models to UD 2.5

### PR DESCRIPTION
**Pull request by asajatovic**
- Update default language models to versions trained on Universal Dependencies 2.5

- Refactor code (mostly add type hints)

- Update tests

- Update README.md

- Update LICENSE

### CODE REVIEW

**Review by mttk — APPROVED** [review]
LGTM

**Comment by BramVanroy** [comment]
Quick question, is this part of the latest PyPi release? Thanks

**Comment by asajatovic** [comment]
> Quick question, is this part of the latest PyPi release? Thanks

Quick answer: yes (see [latest release notes](https://github.com/TakeLab/spacy-udpipe/releases/tag/v0.2.0)) :smiley:

**Comment by BramVanroy** [comment]
Ah, great. I wasn't sure whether these release are also pushed to PyPi immediately. Thanks!

**Pull request merged**
